name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
          major_pattern: "major"
          minur_pattern: "feat"
          
            
          
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        #docker login -u $DOCKER_USER -p $DOCKER_PASSWORD | SE PUEDEN AMBOS METODOS PARA RECIBIR USUARIO
        #Y PASSSWORD

    - name: Build Docker Image
      env: 
        NEW_VERSION: ${{ step.version.outputs.version }}
      run: |
        docker build -t sergio62/graphql2:$NEW_VERSION .
        docker build -t sergio62/graphql2:latest .

    - name: Push Docker Image
      env: 
        NEW_VERSION: ${{ step.version.outputs.version }}
      run: |
        docker push sergio62/graphql2:$NEW_VERSION
        docker push sergio62/graphql2:latest
